### ISSUE TITLE
Error with different path format

### ISSUE THREAD

**Issue by Oscurodrago** [jlecker/django-responsive-images#6] opened 2022-01-28 23:40 UTC
i found a bug problem...  maybe is a bug for django-responsive-images

on some OS there is no problem if image path inside database is:

`media\images\myimage.jpg` 

or 

`media/images/myimage.jpg` 

but in other OS ( like unix in raspberry pi ) django-responsive-images works only if path is with `/` so when it try to modify/copy an image dosen't founds it and trigger an error
(instead on Windows a path `/` is same as `\` )

note: for Browsers there is no difference for :`<img src="media\images\myimage.jpg">` and `<img src="media/images/myimage.jpg">`  both works well

so in a template if image.path have wrong slashes like `media\images\myimage.jpg` on unix/raspberrypi 
`<img src="{{item.img.url}}">` this works and 
`<img src="{% src item.img 150x300 nocrop %}">` this trigger an error
 instead on windows both solutions works works anyway

**Comment by jlecker** [comment] 2022-01-31 22:04
Attempting to guess file paths is far beyond of the scope of this package.

Any package that reads files from the file system is going to have problems if the paths in your database are not consistent. I am not surprised that you are having problems if you are trying to run from the same database on both Windows and Unix.

Closing, as this is not a bug (for me, anyway).

**Closed as completed by jlecker** 2022-01-31 22:04 UTC
