### ISSUE TITLE
FileNotFoundError at <URL_PATH>

### ISSUE THREAD

**Issue by omiid-ad** [jlecker/django-responsive-images#5] opened 2022-01-12 10:30 UTC
Hi,
Recently i keep getting 500 errors with this title:
`FileNotFoundError at <URL_PATH> | [Errno 2] No such file or directory: '/home2/seniktvc/senikgroup/media/-6255899800163691280_120.jpg'`

I don't know why i keep getting this error, and i don't know how to reproduce it, but the thing that i'm sure about is that there is something wrong somewhere in your package.
I can send you full log (`traceback`) of the error if you want.
Thanks in advance ~

**Comment by jlecker** [comment] 2022-01-12 16:46
This app works on existing images in your project. I know that the file path you have shared is not for a file generated by this app, so it appears you are trying to resize an image that doesn't exist.

Where is that path coming from? Usually you want to point to an ImageField on one of the models in your app. Make sure that the original image file exists and can be accessed by Django in your media directory.

**Comment by omiid-ad** [comment] 2022-01-14 09:09
I know that. i have a `Profile` model which has a `avatar` as an `ImageField`, and i think this error occurs when a user tries to change his avatar image. And i'm using `DbCaching` in django, can it cause this problem ? (ex: user changed his avatar photo, but your package tries to resize the previous (old) image which does not exist! )

**Comment by jlecker** [comment] 2022-01-15 04:19
If this error occurs when updating one of your models, then I don't see how it could be a problem in this package.

Does the traceback actually show an error in this code? If there is a bug, I will need more context as to what you are doing with the package. Are you using the template tags? Can you share the relevant code?

**Comment by omiid-ad** [comment] 2022-01-23 18:00
Yes, i'm using template tags, plus using `cache` template tags (still i think there is something wrong with caching + your package when using both together).

here is the `traceback` of the error:

```
Traceback (most recent call last):
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home2/seniktvc/senikgroup/music/views.py", line 652, in top_artists
    return render(request, 'music/top-artists.html', context)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/responsive_images/templatetags/responsive_images.py", line 55, in render
    resized_list = get_sized_images(image, self.sizes, self.crop)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/responsive_images/utils.py", line 21, in get_sized_images
    width = min(width, image.width)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/core/files/images.py", line 19, in width
    return self._get_image_dimensions()[0]
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/core/files/images.py", line 28, in _get_image_dimensions
    self.open()
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/db/models/fields/files.py", line 74, in open
    self.file = self.storage.open(self.name, mode)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/core/files/storage.py", line 36, in open
    return self._open(name, mode)
  File "/home2/seniktvc/virtualenv/senikgroup/3.6/lib/python3.6/site-packages/django/core/files/storage.py", line 231, in _open
    return File(open(self.path(name), mode))
 
Exception Type: FileNotFoundError at /top_artists/
Exception Value: [Errno 2] No such file or directory: '/home2/seniktvc/senikgroup/media/artists/avatars/1d20bede-7c47-11ec-8c3f-901b0ea4a539.jpg'
Request information:
USER: AnonymousUser
```

**Comment by Oscurodrago** [comment] 2022-01-26 08:38
i have same problem, on local it's works but when i try put it online, it dosen't work.... it say he can't find file but it exist !!
i've opened a question here
https://stackoverflow.com/questions/70850384/django-respondive-images-dosent-find-files-when-not-in-local

**Comment by jlecker** [comment] 2022-01-26 16:58
Both of these problems are caused by passing a path to a file that does not exist. This is not something I can magically fix. The package does not have access to the rest of your stack, caching etc. It simply operates on the images that you give to it. Pass a valid file path and it will work.

@omiid-ad You can clearly see from the traceback that responsive_images is just trying to open the file path that was given to it. Of course it is not going to work if you do not pass a valid file. You still haven't shared where you are getting the path from, so I can't really make a guess as to your problem there. FWIW I do not think it is likely to be caused by the `{% cache %}` tag either, which only caches template fragments and does not operate on files.

@Oscurodrago I'm guessing you were working with local files, and when you deployed, you did not upload your media files to the expected location. Or maybe something is not configured correctly.

I have seen no evidence of a bug in THIS package, so I am closing. If either of you can provide a test case demonstrating an an actual problem with this code, I will gladly take another look.

**Closed as completed by jlecker** 2022-01-26 16:58 UTC
